### ISSUE TITLE
Cannot use the addon on Firefox

### ISSUE THREAD

**Issue by tungvn** [clockify/browser-extension#10]
I cannot use the addon on Firefox.

Screenshot:
![Untitled](https://user-images.githubusercontent.com/7405101/60164789-6741f380-9828-11e9-913c-c8af52e31579.png)

Here is the version of the addon.
![image](https://user-images.githubusercontent.com/7405101/60164685-382b8200-9828-11e9-941a-fc2722d58754.png)
And Firefox version
![image](https://user-images.githubusercontent.com/7405101/60164845-7a54c380-9828-11e9-86bc-349c619c8708.png)

**Comment by cedomirm1990** [comment]
Thanks for reporting this, Ngoc Tung Vu!

It seems like issue with automatic login from website. Could you close browser tab with clockify.me and try to reopen addon. It will be fixed soon in some next version.

Cheers!

**Comment by tungvn** [comment]
Yea. I tried in many ways.
- Close the browser tab clockify.me and try to reopen the addon
- Re-install the addon
- Re-login clockify.me and try to reopen the addon
- Try to open addon in private browser
But no way made the addon work again

Hope it fixed soon. I am looking forward to the next version

**Comment by cedomirm1990** [comment]
We have tried to reproduce the problem. We installed the same version of Firefox you are using and everything is working correctly. Please try reinstalling Firefox and see if it works.

Cheers!

**Comment by tungvn** [comment]
Yea, the good news. This addon is working again.
But I think we need to find the hidden issue here :)

**Comment by cedomirm1990** [comment]
Could you send username you are using on our platform on support@clockify.me?

Cheers!

**Comment by tungvn** [comment]
Hmm, I think it's no because I signed the non-disclosure agreement with the client.
But you can find the user with the username tung.vu@*******.agency.
Thanks!
