### ISSUE TITLE
Manage Engine integration removed

### ISSUE THREAD

**Issue by carloshjunior** [clockify/browser-extension#102]
@aleksandar-olic your last [release ](https://github.com/clockify/browser-extension/commit/789f30208fcf81b335e737985dd4b0d0aaf119fe) the manage engine integration was removed and it's working properly.

There was any reason for that?

**Comment by aleksandar-olic** [comment]
No special reason. We've cleaned up some integrations that were no longer working / were not used. Feel free to add again and send us a PR.
