### ISSUE TITLE
Firefox addon v1.8.91 was wrongly released in the past?

### ISSUE THREAD

**Issue by gionn** [clockify/browser-extension#120]
Hi,

don't know how it happened, but my firefox had installed the v1.8.91 clockify addon since March, and I wasn't receiving any updates since then (probably due to version number being greater than the latest version number).

A workaround is to manually reinstall the firefox extension.

**Comment by aleksandar-olic** [comment]
Hm, that's strange, Firefox Store doesn't allow having the latest version be lower than any previous release. You can see all the versions here: https://addons.mozilla.org/en-US/developers/addon/clockify-time-tracker/versions

The only thing that comes to mind is maybe a custom version.
