### ISSUE TITLE
Asana project mapping issue

### ISSUE THREAD

**Issue by armellarcier** [clockify/browser-extension#121]
Hi!
I'm having a problem with an Asana project mapped to the wrong Clockify project.
Whenever I start a timer from Asana, project A, it starts it with project "B" in Clockify.
I even tried deleting project B from Clockify. Still creates a new project B the next time I start the timer from Asana.

Every team member has the problem for that project.

How do we clear Asana/Clockify mappings ??

**Comment by aleksandar-olic** [comment]
We're unable to reproduce this. The extension doesn't do any mapping. It simply reads the text that's in the project section and then checks if there's a project with the same name in Clockify (if there's none, it creates one if enabled in extension's settings).

Maybe a video would help? Or concrete steps to reproduce on a new Asana account.

**Comment by armellarcier** [comment]
The problem seems to have resolved itself. Thanks for your quick reply!
