### ISSUE TITLE
Asana subtasks don't get mapped to the project of parent task

### ISSUE THREAD

**Issue by armellarcier** [clockify/browser-extension#123]
I know subtasks are not mapped to a project in Asana (they can but that's odd).

I'd like to be able to start a timer from a subtask and get a task created in Clockify, associated to the project of the parent task in asana.

The clockify task could have a name containing both the parent task's name and the subtask's.

**Comment by aleksandar-olic** [comment]
Hm, I think this actually works. If you start a timer on an Asana subtask:

- Asana subtask is mapped to Clockify description
- Asana parent task is mapped to Clockify task
- Asana project is mapped to Clockify project 

Just make sure you have the necessary tasks already created, or allow team members to create tasks in workspace settings and instruct them to check "Integrations can create projects/tasks" in the extension's Settings.
