### ISSUE TITLE
environment.webSocket is undefined - Trying to add integration for plutio.com

### ISSUE THREAD

**Issue by Amjad992** [clockify/browser-extension#127]
Hello guys,

I am trying to add an integration for a project management software called plutio.com

I have Node: version **12.16.1**
I have NPM: version **6.14.3**
I installed Ruby with development kit: version **2.7.2p137 (2020-10-01 revision 5445e04352) [x64-mingw32]**
I installed Compass: version **1.0.3 (Polaris)**

I **built the chrome and firefox extensions** following the instructions in the readme file (**npm run compile.dev.chrome** and **npm run compile.dev.firefox**), it all went smoothly without any errors

When I load the extensions in the browsers it shows me errors of undefined value

1) In chrome it shows _Uncaught TypeError: Cannot read property 'endpoint' of undefined_ for the setWebSocketParamsToStorage function in [src/application.js](https://github.com/clockify/browser-extension/blob/master/src/application.js) file

2) In firefox it shows _Uncaught TypeError: environment.webSocket is undefined_ for the same function in application.js file

The lines that causes the errors are
`localStorageService.set( "webSocketEndpoint", environment.webSocket.endpoint,getLocalStorageEnums().PERMANENT_PREFIX);
localStorageService.set("webSocketClientId",environment.webSocket.clientId,getLocalStorageEnums().PERMANENT_PREFIX);`

When I tracked the environment.webSocket object, I found it returned from [src/environment.dev.js](https://github.com/clockify/browser-extension/blob/master/src/environment.dev.js) and it has the value of
```
{
    production: true,
    endpoint: 'https://global.api.clockify.me',
    home: 'https://clockify.me',
    signUp: 'https://clockify.me/signup',
    resetPassword: 'https://clockify.me/reset-password',
    startButton:'START',
    stopButton:'STOP',
    terms: 'https://clockify.me/terms',
    webClientId: 'yout-clientIt-from-google-api-console',
    redirectUriOauthChromeExtension: "login/extension/chrome/oauth2",
    redirectUriOauthFirefoxExtension: "login/extension/firefox/oauth2"
}
```

What I am missing here please, isn't there supposed to be a value for the webSocket in the environment? am I supposed to provide that myself or what and also am I supposed to create an app or something on google console?!

https://www.loom.com/share/7bb34debea8b4b03bd3f4f53a1ba60b9

Thank you

**Comment by aleksandar-olic** [comment]
production code and github code wasn't synced, maybe that's why it didn't work. could you pull the latest changes and try again?

**Comment by Amjad992** [comment]
@aleksandar-olic 

I have pulled the changes and now it's working fine, however, it's throwing another set of errors (although I faced no issues yet because of these, I'll add the screenshot just for reference for the team if needed and I'll be closing the issue)

Thank you

![errors](https://user-images.githubusercontent.com/15037674/97444200-b1237800-194d-11eb-9445-f4173b9d1be7.JPG)

**Comment by aleksandar-olic** [comment]
Hm, we haven't noticed this. Could you try removing `unsafe-eval` from the manifest file and see if that may help?

**Comment by Amjad992** [comment]
it doesn't seem to make a difference in terms of removing the errors and warning

attached below screenshots of the errors

**Firefox:**
![firefox](https://user-images.githubusercontent.com/15037674/97773262-0dfe7880-1b70-11eb-8d4d-ab476db0df3d.JPG)


**Chrome:**
![chrome1](https://user-images.githubusercontent.com/15037674/97773648-700cad00-1b73-11eb-86fb-df7fa38cdfaa.JPG)
![chrome2](https://user-images.githubusercontent.com/15037674/97773649-71d67080-1b73-11eb-95b2-2db7561f5399.JPG)
![chrome3](https://user-images.githubusercontent.com/15037674/97773652-726f0700-1b73-11eb-9aa2-d1ac277eb39a.JPG)
In Chrome all the errors are in these 2 lines
![chromeA](https://user-images.githubusercontent.com/15037674/97773653-73079d80-1b73-11eb-93f7-c33579a1319d.JPG)
![chromeB](https://user-images.githubusercontent.com/15037674/97773654-73079d80-1b73-11eb-9f3c-833075540db5.JPG)






and by the way as you already know your live extension has none of these errors or warnings
