### ISSUE TITLE
Cerb integration broken - cerb.js missing from Chrome + Firefox web store extensions

### ISSUE THREAD

**Issue by Tim-Blyth-SiteHost** [clockify/browser-extension#132]
## The Issue
Cerb integration was added in https://github.com/clockify/browser-extension/pull/79, but when attempting to use the browser extension from either the Firefox or Chrome web stores, the integration doesn't work (The "Start Timer" button isn't created in the Cerb action bar as is expected)

## Investigation + Findings
To investigate, I used [Chrome Extension Source Viewer](https://chrome.google.com/webstore/detail/chrome-extension-source-v/jifpbeccnghkjeaalbbjmodiffmgedin) to have a look inside. What I spotted is that cerb.js is missing, but the inclusion of cerb.ai in integrations.json is present (both are from the same PR).

## Theories + Possible Solutions
Is it possible that the cerb.js is somehow not included as part of your browser extension compilation process?

According to the version property of the [manifest.json](https://github.com/clockify/browser-extension/blob/master/manifest.chrome.dev.json) file, the repo is on version `1.8.53` while the source of the Web Store  is at `1.8.59`; is it possible cerb.js was lost in one of these updates that's not in the repo?

I'm happy to make any changes necessary to remedy this problem, as I would like to get the integration functioning as soon as possible.

Cheers

**Comment by aleksandar-olic** [comment]
Hm, for some reason the file disappeared from the production release. We have restored it, so it should be available with the next release (eta within a week)
