### ISSUE TITLE
Next Release Timeline Update

### ISSUE THREAD

**Issue by Tim-Blyth-SiteHost** [clockify/browser-extension#133]
The Cerb integration is broken as mentioned in https://github.com/clockify/browser-extension/issues/132, which was closed around two weeks ago stating

> We have restored it, so it should be available with the next release (eta within a week)

Would it be possible to get a timeline update on when the next release is planned? We're looking forward to using the Cerb integration.

Cheers.

**Comment by aleksandar-olic** [comment]
Sorry about that, we had a major feature and one bug fix in development, so we didn't have a new release yet. It should be within a week or two, by the end of 2020 :)
