### ISSUE TITLE
Disable !important on webkit scrollbar

### ISSUE THREAD

**Issue by orange1337** [clockify/browser-extension#144]
::-webkit-scrollbar-thumb {
    background: rgb(3, 169, 244) !important;
}

Please disable !important from scroll bar styles, this "feature" has broken scrollbars color for all services.

**Comment by andressltz** [comment]
It's breaking all the websites visited

**Comment by aleksandar-olic** [comment]
Sorry about that. It's been fixed. It should be live on the Chrome/Firefox store in a couple of hours (v1.8.66).

**Comment by orange1337** [comment]
Thanks for the quick fix 👍
