### ISSUE TITLE
'Start timer' from Reminder notification does not work

### ISSUE THREAD

**Issue by mabi** [clockify/browser-extension#166]
version 1.8.88

Clicking 'Start timer' from Reminder notification does not work with the following error

`
Error in event handler: TypeError: this.startTimer is not a function
    at buttonClickedListener (chrome-extension://pmjeegjhjdlccodhacdgbgfagbpmccpe/contentScripts/notification-background.js:12:22)
`

maybe is it `TimeEntry.startTimer('');` instead of `this.startTimer('');`?

**Comment by 7saraK** [comment]
Hi @mabi, Could you please tell us if this problem still persists?

**Comment by mabi** [comment]
> Hi @mabi, Could you please tell us if this problem still persists?

@7saraK, looks solved, tested with version 2.2.2. Thank you.

**Comment by 7saraK** [comment]
@mabi Great news. Thank you for confirming. Feel free to reach us at support@clockify.me if you have any other questions. Cheers!
