### ISSUE TITLE
Browser extension messes up styling on Google Calendar

### ISSUE THREAD

**Issue by smsalisbury** [clockify/browser-extension#176]
The browser extension is making parts of Google Calendar hard to read. If the Google Calendar integration is disabled in the extension settings the styling is fine. I didn't see this issues the last time I used the extension (around a month ago), so I'm not sure if it was a change to the extension or a change to the Google Calendar UI that caused the incompatibility.

![image](https://user-images.githubusercontent.com/8053224/148102730-f4a0ceb2-9c74-4be8-8274-68c42422a7dd.png)
![image](https://user-images.githubusercontent.com/8053224/148102817-bd920261-e074-495d-800f-75952cf6f420.png)

These screenshots were taken using Firefox 95.0.1 and extension version 1.9.6.

**Comment by strahinjaclockify** [comment]
Hi Spencer, thanks for letting us know about Clockify integration's UI issues in Google Calendar. I've forwarded the info and the screenshots to the dev team and will get back to you as soon as the issue is resolved.

**Comment by strahinjaclockify** [comment]
Hi Spencer, following up on my previous comment - please update the Clockify extension to version 1.9.7, UI issues you mentioned are fixed now.

Thanks again for reporting, please let us know if we can help any further 🙌

**Comment by smsalisbury** [comment]
Thank you for the fix and the responsiveness!
