### ISSUE TITLE
Trouble with gitea integration

### ISSUE THREAD

**Issue by slavb18** [clockify/browser-extension#181]
Cannot enable gitea integration in chrome plugin:
I have added custom domain
![image](https://user-images.githubusercontent.com/2534896/156732319-817f635e-f26f-4ada-9a3d-5a2b7126b352.png)

But I cannot see clockify Start timer button:

![image](https://user-images.githubusercontent.com/2534896/156732449-98168573-e155-4264-9a2e-c8a712907da6.png)

Tried other custom domains too, without success

**Comment by strahinjaclockify** [comment]
Hi @slavb18, thanks for letting us know about the issue! I forwarded the information to our dev team, and will get back to you as soon as we fix the bug 🙌🏼

**Comment by slavb18** [comment]
> Hi @slavb18, thanks for letting us know about the issue! I forwarded the information to our dev team, and will get back to you as soon as we fix the bug 🙌🏼

Hi!
Any chance this bug will be soon fixed

**Comment by slavb18** [comment]
GItea integration now working with custom domain, thank you!
