### ISSUE TITLE
2.2.0 breaks letter casing in a lot of places!

### ISSUE THREAD

**Issue by madhead** [clockify/browser-extension#188]
## Description
This change breaks letter casing for a lot of buttons on a lot of sites (GitHub and Trello, for instance).

https://github.com/clockify/browser-extension/commit/c8472ff0ce173d117568ba8ac0a2335a742acdbf#diff-0136b1b6f58de6647569e3ccfbd5a01e8d9a4c661a2688d60a9c2e77c9b37221

![image](https://user-images.githubusercontent.com/577360/165660994-15080079-fb00-4881-b12e-7d791ff12dfb.png)

## How did I find it out

Select a button with a broken case:

![image](https://user-images.githubusercontent.com/577360/165661721-fdc35588-74c2-4d5c-a8f4-fb8e8d24e197.png)

Find this style:

```css
button {
  text-transform: uppercase;
}
```

It definitely comes from the Clockify extension (the link `style.css` at the topwright corner opens the whole file and it belongs to Clockify extension).

## Browser Info

| Name       | Firefox                                                                      |
|------------|------------------------------------------------------------------------------|
| Version    | 99.0                                                                         |
| User Agent | Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:99.0) Gecko/20100101 Firefox/99.0 |
| OS         | Linux 5.14.0-1033-oem #36-Ubuntu SMP Mon Apr 4 15:15:49 UTC 2022             |
| OS Theme   | Yaru-dark / Yaru                                                             |

**Comment by 7saraK** [comment]
Hi there, thank you for reporting this. 

Kindly note this was fixed with v2.1.1 of the Clockify extension. Feel free to update the extension, and in case you still encounter the same issue contact us at support@clockify.me so we can troubleshoot this further. 
Cheers!

**Comment by madhead** [comment]
@7saraK, indeed, seems to be fixed now. Thanks!
