### ISSUE TITLE
Azure Devops Services integration not working

### ISSUE THREAD

**Issue by janisklavins** [clockify/browser-extension#196]
When Clickin on "Start Timer" on Azure Devops. The extension does not add a task and does not start a timer.
Console provides the following error:

Uncaught ReferenceError: tagNames is not defined
    at tagNames (azure.js:30:23)
    at invokeIfFunction (clockifyButton.js:211:16)
    at objInvokeIfFunction (clockifyButton.js:219:23)
    at buttonClicked (clockifyButton.js:324:37)
    at button.onclick (clockifyButton.js:103:18)
tagNames @ azure.js:30
invokeIfFunction @ clockifyButton.js:211
objInvokeIfFunction @ clockifyButton.js:219
buttonClicked @ clockifyButton.js:324
button.onclick @ clockifyButton.js:103

Browser: Chrome
Extension Version: 2.5.1

**Comment by strahinjaclockify** [comment]
Hey @janisklavins, thanks for letting us know about this issue 🙌🏼 We'll deploy a fix for it in the next version 2.6.0.

**Comment by 7saraK** [comment]
@janisklavins Hi there, just letting you know that the team has released version 2.6.0 of the browser extension with the fix for this issue. Hopefully, the fix works on your side as well. Cheers!
