### ISSUE TITLE
Starting a timer while having a default project selected does not allow user input

### ISSUE THREAD

**Issue by esjch2020** [clockify/browser-extension#198]
EDGE Browser with Chrome version of Clockify since the EDGE Extension Store hasn't been updated since 2021.
When you start a timer, it no longer selects the default project or user input. Just a blank screen.

![image](https://user-images.githubusercontent.com/66798474/181366325-88196aa6-c354-414f-a97c-4c39b2eb2d65.png)

In configuration I have a default project set but this is no longer selected.

To reproduce:
0) Set a default project
1) Click Start Timer
---Immediately you see the blank screen as above.
2) Click Clockify Extension and see the timer running

There is no text entry box and no way to select the project except by navigating to the website.

**Comment by esjch2020** [comment]
I discovered more information. As soon as I turn off Default Project, it allows me to edit the entry.

**Comment by 7saraK** [comment]
@esjch2020 Hi there, thank you for reporting this. Can you please try uninstalling the extension > clearing cache and cookies > reinstalling the extension again > try to start the timer with the default project setup again? 
Please let me know if it helped. Cheers!

**Comment by esjch2020** [comment]
@7saraK Pardon the delay. I went through the process of removing extension, clearing cache and then adding it again and the same behavior exists as soon as a start a timer after selecting a default project. As soon as I remove the default project in the settings, I can edit the entry within the extension.

**Comment by 7saraK** [comment]
Thank you for your reply, @esjch2020. Can you please share a link with me from where you have downloaded your Edge extension?

**Comment by esjch2020** [comment]
https://chrome.google.com/webstore/detail/clockify-time-tracker/pmjeegjhjdlccodhacdgbgfagbpmccpe?hl=en-US

**Comment by 7saraK** [comment]
Thank you for sharing this with me, @esjch2020. 
Please let me consult the team and I'll update you as soon as possible. Cheers!

**Comment by 7saraK** [comment]
Hi @esjch2020, I just wanted to let you know that the team has released the version of the extension with the fix for the issue you have experienced. 
Please update the extension and let me know if everything is working fine. 
Cheers!

**Comment by esjch2020** [comment]
Yes this seems fixed with the 2.6.9 version of the Extension!
