### ISSUE TITLE
github is no longer working

### ISSUE THREAD

**Issue by wmertens** [clockify/browser-extension#213]
Recently, the extension doesn't work in github any more. Github is still selected in the sites, but in the devtools it doesn't appear as one of the loaded extensions. There are no error messages.

**Comment by 7saraK** [comment]
Hi @wmertens, thank you for letting us know. Could you please try uninstalling the extension > clearing cache once more > installing the extension again?
Please advise, looking forward to your reply.

**Comment by wmertens** [comment]
Thank you, uninstall + reinstall (no idea how to clear cache) worked!
