### ISSUE TITLE
In Gitlab integration use issue reference instead of issue number

### ISSUE THREAD

**Issue by compiaffe** [clockify/browser-extension#24]
When tracking time in Gitlab the clockify.me time entry description field is filled in as such:

```
#${ISSUE_NUMBER} ${ISSUE_TITLE}
```

So a typical entry could be:
```
#134 Review and test new plugin
```

When working with multiple groups or subgroups and thinking to automatically add tags on either the issue or the clockify.me time entry it would be much more useful to use the issue reference instead of the issue number.
References are shown in the right hand sidebar in Gitlab at the very bottom and look like this:
```
my_group/my_project#1
```
or 
```
toplevel_group/first_subgroup/second_subgroup/project_name#issue_number
```

These references are unique for a given gitlab instance and would make it significantly easier to integrate or match work descriptions with Gitlab issue.

**Comment by malizmaj** [comment]
Feel free to add those references and send us a pull request. Alternatively, you can fork the extension, make the changes, and run your custom version of the extension (you'll need to pull new changes every once in a while to manually update your custom extension).

**Comment by mark-monteiro** [comment]
@aleksandar-olic I went ahead and made a pull request to implement this a month ago. Just wanted to bump this issue to see if it can be moved along

**Comment by aleksandar-olic** [comment]
cc @AleksaDoderovic

**Comment by compiaffe** [comment]
Great. Thanks @mark-monteiro

**Comment by AleksandraGacevic** [comment]
@mark-monteiro The request has been merged and it will be available in the next version. Thank you!
