### ISSUE TITLE
With click 3.0 task id's are missing from time slot description

### ISSUE THREAD

**Issue by ericdsd** [clockify/browser-extension#249]
I switched to clickup 3.0 with clockify firefox extension 2.10.2 (mac), and when i click on "Start timer" link the time tracking slot is created mensioning only the title of the task in description.

Before description was :
Name of my task | TASK-ID

Now it is :
Name of the task

I had to rollback to clickup 2 as my tracking relies on task id's.

**Comment by ericdsd** [comment]
Hi Since october 28, the same issue occurs with clickup 2.0, i've also retested with clickup 3.0 and it's still the case.
Using extension version 2.10.4 with firefox 119.0 on mac (Ventura)

**Comment by fabiomsnunes** [comment]
Make a PR to fix this. See https://github.com/clockify/browser-extension/pull/255
