### ISSUE TITLE
Can I have a custom integration with pipefy?

### ISSUE THREAD

**Issue by ricfwolff** [clockify/browser-extension#26]
I was wondering if I could have a custom integration with pipefy.

For instance, I want to get the Project field from a custom field that I have in pipefy. I have html access to it, but I don't want to override your default pipefy integration. Because not everybody will have the same field mapped to the project. It would be something customized to my own integration. Is it possible?

Also, can I send the "Client" to the "createButton" function? There is another custom field in pipefy that I would like to use as the Client of the tracking.

Thank you!

**Comment by malizmaj** [comment]
Things you can map in the integration are: what will Clockify pick up as description (in your case, Pipefy project would be picked up as description in Clockify), and to what project it belongs to (as long as the name of that thing in Pipefy matches an existing project in Clockify, or in your case Client from Pipefy would be project in Clockify). 

You'll have to develop these things yourself, but that's fairly simple. The only inconvenience is that you'll have to run the custom extension yourself and you won't get automatic updates. You'll need to fork the repo, make changes, and have that version installed. When we make an update, you'll need to pull the changes, and generate and install your version of extension yourself.
