### ISSUE TITLE
Zammad.com / .org integration change not merged with integrations.json

### ISSUE THREAD

**Issue by RitchieFarr** [clockify/browser-extension#36]
I previously submitted an integration for zammad.com / zammad.org. This got added but the required change to integrations.json was not merged. The following needs to be added to get this integration working:
`  "zammad.com": {
    "name": "Zammad",
    "link": "*://*.zammad.com/*",
    "script": "zammad.js",
    "clone": false
  },`

**Comment by cedomirm1990** [comment]
Hello RitchieFarr,
Sorry for this problem, it will be fixed in next release.

Cheers!

**Comment by cedomirm1990** [comment]
New release 1.7.6 is live now.

Cheers!

**Comment by RitchieFarr** [comment]
Hi,

This is still missing from the list in recent builds for Chrome. I can see that the source file is correct in git though.
