### ISSUE TITLE
Clockify button doesn't show up in a new List layout in Asana

### ISSUE THREAD

**Issue by honzapav** [clockify/browser-extension#37]
Asana is releasing a [new list layout for project page](https://asana.com/guide/help/views/list). In this view, the clockify button doesn't show up. Is it possible to fix it?
Thanks.

**Comment by cedomirm1990** [comment]
Hello honzapav, 
We are currently working on this issue. It will be fixed in next release.
Thanks for reporting us.

**Comment by mistvan** [comment]
Hi @cedomirm1990 what is next release branch in this repo please? Thanks

**Comment by cedomirm1990** [comment]
New release 1.7.6 is live. You can check now Asana integration. 

Cheers!
