### ISSUE TITLE
In GitLab, get and use project name

### ISSUE THREAD

**Issue by findemor** [clockify/browser-extension#52]
When you click Start Timer, only the ticket number and name are shown, But Project field in Clockify remains empty, so it must be completed after manually. It could be great if it is automatically fulfilled from project name in Gitlab.

**Comment by malizmaj** [comment]
This actually works, but only if you have the project with the same name in both Gitlab and Clockify.

If you don't, you can use something like Zapier to keep stuff in sync (eg. create new repo in Gitlab -> create project in Clockify)
