### ISSUE TITLE
Project Rules

### ISSUE THREAD

**Issue by brentahughes** [clockify/browser-extension#54]
This may be more of a request than an issue so feel free to direct me to the correct place if needed.

The problem I'm having is when clicking start timer from Jira, it may be the same with all integrations as well, it always creates it in the same project. There is no way to dynamically put it in a different project.
 
I've been at a few places that treat time tracking workflows with tickets differently. Some have a single epic with lots of jiras and everything is tracked under the single epic project. Then there are ones that track every ticket in it's on project.
 
I would like to be able to click "Start Timer" and it create it in the project for the ticket rather than setting it's name to the ticket title and putting it in the previous or default project. I currently get around this with a simple cli tool that starts/stops timers and creates the project if it doesn't already exist. It would just be nice if this was an option in the chrome extension.

**My Request**
- Have option to define the default task name rather than the default project (coding, research, testing) and create the task in a project with the same name as the ticket.
- If the project does not exist create it.
- This should be an optional setting so existing behavior is not altered

**Possible Issues**
- Not everybody has permissions to create projects so may need a way to hide this option if the permission does not exist for the user. Or just error if the project doesn't already exists when a timer is started.

**Comment by aleksandar-olic** [comment]
Thanks for the feedback! Could you explain your workflow a bit more so we can better understand why you'd like a new project for every single ticket? (as the intended use case of projects is to group similar time entries and description is for the actual thing ie. ticket, while tasks are like subprojects in case you need a deeper hierarchy).

Also, we plan to build a Jira plug-in which will let you keep both projects and time logs in sync.
