### ISSUE TITLE
Why does the browser extension need access to "read and change all your data on the websites you visit"?

### ISSUE THREAD

**Issue by MartinRiddar** [clockify/browser-extension#55]
There is no description in the chrome web store of why this is needed and such a requirement screams "no go" for me and many others today.
After reading the help article linked in the web store I'm guessing it has to do with the feature "Track time from selected text"?

**Comment by jovana-k** [comment]
We use the "Read and change all your data on the websites you visit" permission only for putting a timer button on other websites and taking the task's names as a description for the timer. If you don't wish to see the button on some websites, you can disable it in extension's Settings>Integrations.

**Comment by MartinRiddar** [comment]
Thank you for the quick response.
