### ISSUE TITLE
Chrome Gmail Issue: Uncaught SyntaxError: Identifier 'aBrowser' has already been declared

### ISSUE THREAD

**Issue by j-d-b** [clockify/browser-extension#59]
After installing the clockify Chrome extension the gmail web app became unusably slow with tens of thousands of 

```
Uncaught SyntaxError: Identifier 'aBrowser' has already been declared
```

errors filling the console.

Disabling the gmail integration fixed this, but obviously at the expense of not being able to trigger a clockify task from the gmail web app. I wasn't using this feature, but wanted to note the issue here.

**Comment by FrankM-Charter** [comment]
I am also seeing this issue while working on an integration for Rally. 

`VM7319 button.js:1 Uncaught SyntaxError: Identifier 'aBrowser' has already been declared
    at VM7306 button.js:1`

**Comment by cvbrian** [comment]
I'm getting that on Notion as well. It isn't loading the button in some places it should be there too.

**Comment by j-d-b** [comment]
Why was this closed? Was it resolved?

**Comment by aleksandar-olic** [comment]
Yep, it's been resolved. It shouldn't appear any more (v1.8.9)
