### ISSUE TITLE
Azure DevOps: On Timer Stop automatic Project Assignment

### ISSUE THREAD

**Issue by lukadt** [clockify/browser-extension#70]
I have enabled Azure DevOps integration and everything is working fine. I have one feature suggestion that is valid for every plugin and not only azure DevOps. Would be possible to automatically assign a project on timer stop?

Basically if the Azure DevOps project match a clockify project name clockify can fill it and stop the timer otherwise the current warning message  _"Can't end entry without project/task/description or tags.Please edit your time entry."_ is displayed.
If you provide me some guidance I could develop on my own and in case give back as I want a solution that is still valid and do not make me lose compatibility with your future plugin updates.
Tnx in advance,
Luca

**Comment by aleksandar-olic** [comment]
If you have the same project in both Clockify and Azure, the project should be automatically assigned each time you hit Start. (This goes for Asana, Trello, and some other integrations too.)

If you wish, you can tinker with [the "project" var's selector](https://github.com/clockify/browser-extension/blob/master/src/integrations/azure.js).

**Comment by lukadt** [comment]
Dear @aleksandar-olic it's working good !!! maybe I could just also fill the task with some custom logic based on work items type ( to assign it to categories such as SW Dev, SW Testing, SW Document) but it would bit a little bit overkilled. Keep up the good work 👍
