### ISSUE TITLE
Actual version

### ISSUE THREAD

**Issue by oksidisko** [clockify/browser-extension#73]
Current master branch version is "1.8.9" (according to  [manifest.chrome.dev.json](https://github.com/clockify/browser-extension/blob/master/manifest.chrome.dev.json#L23))
chrome://extensions/ shows me "1.8.13" (installed from the store)

Does the master branch contain latest release code?

**Comment by aleksandar-olic** [comment]
Yes, the master always has the latest release that's on the Chrome Store (in this case, it's actually 1.8.14. even thought the manifest says it's lower). 

When there's one integration fix, we usually commit it directly without updating the manifest; and when there are multiple updates, we update everything along with the manifest file. Sorry for the confusion!
