### ISSUE TITLE
TickTick Start Timer not filling in description

### ISSUE THREAD

**Issue by dougcooper** [clockify/browser-extension#86]
Expected: When select a task and click 'Start Timer' a time entry is created with a description that matches the title of the task.

Actual: The timer is started but there is not description.

This was working fine then stopped all of a sudden. I verified the functionality in trello and it works as expected when starting a timer from a card.

Chrome (windows) Version 81.0.4044.138 (Official Build) (32-bit)
Extension version 1.8.18

**Comment by aleksandar-olic** [comment]
Fixed (v1.8.19)
