### ISSUE TITLE
Atlassian integration not getting Task-ID anymore

### ISSUE THREAD

**Issue by rmausz82** [clockify/browser-extension#87]
the selector for getting the Task-ID seeems to be wrong. I just got 
I changed the selector in line 53 from 
$('div > div > div > div > div > div:first-child > div > div:first-child > div', elem);

to 
 
$('div > div > div > div > div > div:first-child > div > div:first-child > div > div:last-child', elem);

to make it work again.

I am using Jira-cloud

**Comment by aleksandar-olic** [comment]
Fixed (v.1.8.20). It can now also select/create task based on task id.
