### ISSUE TITLE
security holding package

### ISSUE THREAD

**Issue by DanielRuf** [clockify/browser-extension#9]
Hi,

it seems you have accidentally added `fs` but this is not a package on npmjs, `fs` is an internal NodeJS module.

https://github.com/clockify/browser-extension/blob/master/package.json#L30

See https://nodejs.org/api/fs.html

You might want to remove it using `npm uninstall fs`.

**Comment by cedomirm1990** [comment]
Thanks for reporting this, DanielRuf!

You're right, it will be switched to dev dependencies in next release.

Cheers!

**Comment by DanielRuf** [comment]
Not sure if you have correctly understood it but `fs` is not a real dependency and has no code as it is a core part of `node`.

**Comment by cedomirm1990** [comment]
I understood now, thanks again, it will be removed in next release. 
So i will close this issue now
