### ISSUE TITLE
Compile Chrome extension without Developer mode

### ISSUE THREAD

**Issue by DePalmo** [clockify/browser-extension#91]
Hello,

Some time ago I made a PR #49 and it was integrated into live version, but then Jira changed and you removed my updates. Unfortunately we're still on AUI 6.0.5 and newest updates do not work for me.

Because of that I removed live extension that I downloaded from Chrome's Play Store and compiled my own version but now each time I start Chrome, there's a popup notification about Developer mode being enabled. Is it possible for me to compile a "live" version and import it into Chrome without the Developer mode being active? If possible, would really appreciate steps required to do so.

**Comment by aleksandar-olic** [comment]
Hm, not sure, this is more of a Chrome's settings. You can [try something like this](https://stackoverflow.com/questions/23055651/disable-developer-mode-extensions-pop-up-in-chrome)

**Comment by DePalmo** [comment]
Thanks for the proposal, will check it out.
