### ISSUE TITLE
Not available on addons.mozilla.org

### ISSUE THREAD

**Issue by podruh** [clockify/browser-extension#92]
Hi, I tried to download the extension to new machine, but it seems that the link on your page (https://addons.mozilla.org/en-US/firefox/addon/clockify-time-tracker/) is not working. 
Did you pull the extension? 
I really don't want to spend time compiling it.

**Comment by aleksandar-olic** [comment]
The add-on is currently under review. We got a review saying that it shouldn't use "unsafe-eval" flag so we're refactoring code to make it work without it. We hope it will be live by the end of this or next week.
