### ISSUE TITLE
Unable to continue after stop a timer

### ISSUE THREAD

**Issue by picolloo** [clockify/browser-extension#96]
When I stop the timer for a while and then get back to it, the extension creates a new timer instead of continuing the old one.

**Comment by aleksandar-olic** [comment]
It starts a timer for a new time entry? Or does it place a new "Start timer" button (so the page has two buttons)?

If it's the first, that's by design. If it is latter, where does it happen?

**Comment by picolloo** [comment]
This is how the timer becomes when I get back to a paused timer

![image](https://user-images.githubusercontent.com/29408363/85209897-ff769980-b311-11ea-955a-8d1c6d05e3f1.png)

**Comment by aleksandar-olic** [comment]
I see, That's by design, it's not a bug. Clockify doesn't have a pause, Instead, a new time entry is created every time a timer is stopped.
