### ISSUE TITLE
Freshdesk update has integration stop working

### ISSUE THREAD

**Issue by andre-faria** [clockify/browser-extension#98]
Recently update on freshdesk has broken the integration, Clockfy button appear below description and when pushing it the timer starst just with ticket number without description [#00000].

**Comment by aleksandar-olic** [comment]
Fixed (v1.8.30)

**Comment by andre-faria** [comment]
Thanks for the update after this update when I stated the ticket was between "[" like "[#ticket]".

I´ve changed it in my file, can you update here? (I don´t know how).

`clockifyButton.render('.page-actions__left:not(.clockify)', { observe: true }, function (elem) {
        const desc = $(".ticket-subject-heading").innerText;
        const ticket = $(".breadcrumb__item.active").innerText;
        const link = clockifyButton.createButton("[#" + ticket + "] " + desc);
        link.style.marginLeft = "10px";
        elem.append(link);
});`
